# Generated by Django 3.0.5 on 2020-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles_app', '0002_auto_20200406_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='watched_movies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wishlisted_movies',
            field=models.TextField(null=True),
        ),
    ]
